#!/bin/bash

if [ "x$gbtools_host_name" == "x" ]; then
    gbtools_host_name=$(hostname)
fi

# Make a prefix.
# Usage your_var=$(gbtools_make_prefix) 
function gbtools_make_prefix
{
    now=$(date +%H:%M:%S)

    $ECHO "[$gbtools_host_name $SCRIPT_NAME ($now)] $@"
}

# Usage: gbtools_message_err Your Message
function gbtools_message_err
{
    $ECHO "$(gbtools_make_prefix) $@" >&2
}

# Usage: gbtools_message_exit Your Message
function gbtools_message_exit
{
    gbtools_message_err "$@"
    exit 1;
}


INSTALL_DIR=$1


SCRIPT_NAME=$(basename $0)
INITIAL_DIR=$(pwd)
 SCRIPT_DIR=$(dirname $0)
if ! echo $SCRIPT_DIR | egrep -q "(^)/" ; then
   BASE_DIR=$INITIAL_DIR/$SCRIPT_DIR
else
   BASE_DIR=$SCRIPT_DIR
fi


# run the configure.......watch out for the quoting, sometimes we want the variable to
# be interpreted as a single cmdline arg, sometimes as multiple ones.

$BASE_DIR/configure \
$INSTALL_DIR \
"$CC_param" "$CFLAGS_param" "$LDFLAGS_param" "$@" || message_exit "configure script failed."


#
# This adds the subdirectories to the build directory. 
#
#ln -s ../../htslib-develop
#cp -r $BASE_DIR/gbtoolsGUI .

exit 0
